site_name: Fullstack week - Docs
theme:
   name: material
   language: en
plugins:
  - search
nav:
  - Introduction: 'index.md'
  - Data: 'data.md'
  - Organization: 'organization.md'
  - Running: 'running.md'